version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: RawMaterials
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    container_name: rawmaterials-
    
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - client
    container_name: rawmaterials-server

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    container_name: rawmaterials-client
